access_request_allowed_event_type: access_request_allowed
access_request_created_event_type: access_request_created
access_request_denied_event_type: access_request_denied
access_request_events_topic: access_request_events
central_data_stewardship_email: test@test.abc
db_connection_str: '**********'
db_name: nos
generate_correlation_id: true
helpdesk_email: test@test.def
iva_state_changed_event_topic: ivas
iva_state_changed_event_type: iva_state_changed
kafka_max_message_size: 1048576
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
log_traceback: true
notification_event_topic: notification_events
notification_event_type: notification
second_factor_recreated_event_topic: auth
second_factor_recreated_event_type: second_factor_recreated
service_instance_id: '1'
service_name: nos
user_events_topic: users
