access_request_allowed_type: access_request_allowed
access_request_created_type: access_request_created
access_request_denied_type: access_request_denied
access_request_events_topic: access_request_events
central_data_stewardship_email: test@test.abc
db_connection_str: '**********'
db_name: users
generate_correlation_id: true
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
notification_event_topic: notification_events
notification_event_type: notification
service_instance_id: '1'
service_name: nos
