service_instance_id: "1"
central_data_stewardship_email: "test@test.abc"
helpdesk_email: "test@test.def"
db_connection_str: mongodb://localhost:27017
db_name: nos
kafka_servers: ["kafka:9092"]
access_request_events_topic: access_request_events
access_request_created_event_type: access_request_created
access_request_allowed_event_type: access_request_allowed
access_request_denied_event_type: access_request_denied
notification_event_type: notification
notification_event_topic: notification_events
file_registered_event_topic: internal_file_registry
file_registered_event_type: file_registered
iva_state_changed_event_topic: ivas
iva_state_changed_event_type: iva_state_changed
user_events_topic: users
second_factor_recreated_event_topic: auth
second_factor_recreated_event_type: second_factor_recreated
