[project]
name = "nos"
version = "4.0.0"
description = "The Notification Orchestration Service controls the creation of notification events."
dependencies = [
    "typer >= 0.9.0",
    "ghga-event-schemas >= 4.1.0",
    "hexkit[akafka,mongodb] >= 4.1",
    "pydantic[email]>=2, <3"
]

[project.urls]
Repository = "https://github.com/ghga-de/notification-orchestration-service"

[project.scripts]
nos = "nos.__main__:run"
