[project]
name = "nos"
version = "0.1.0"
description = "The Notification Orchestration Service controls the creation of notification events."
dependencies = [
    "typer >= 0.9.0",
    "ghga-service-commons[api] >= 3.0.0",
    "ghga-event-schemas >= 3.0.0",
    "hexkit[akafka,s3,mongodb] >= 2.1.0"
]

[project.urls]
Repository = "https://github.com/ghga-de/notification-orchestration-service"

[project.scripts]
# please adapt to package name
nos = "nos.__main__:run"
