[project]
name = "nos"
version = "7.0.0"
description = "The Notification Orchestration Service controls the creation of notification events."
dependencies = [
    "typer >= 0.16",
    "ghga-event-schemas ~= 10.0",
    "hexkit[akafka,mongodb,opentelemetry] >= 6.0",
    "pydantic[email]>=2, <3"
]

[project.urls]
Repository = "https://github.com/ghga-de/notification-orchestration-service"

[project.scripts]
nos = "nos.__main__:run"
